name: Sync Issue to Azure DevOps work item

on:
  issues:
    types: [labeled]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Syncing to Azure DevOps
    steps:       
    - uses: champnic/github-actions-issue-to-work-item@simple-sync
      env:
        github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"  
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
      with:
        label: 'tracked'
        ado_organization: 'microsoft'
        ado_project: 'Edge'
        ado_area_path: 'Edge\Dev Experience\WebView'
        ado_tags: 'WV2_GitHub'
